/*
 * Auto-generated by DataSmith
 * DO NOT MODIFY
 */

namespace Baruah.DataSmith.Sample
{
    public static class DataContext
    {
        private static bool _initialized;

        public static InventoryItemModel InventoryItemModel { get; private set; }
        public static PlayerStatsModel PlayerStatsModel { get; private set; }

        public static void Initialize()
        {
            if (_initialized) return;
            _initialized = true;

            InventoryItemModel = new InventoryItemModel();
            PlayerStatsModel = new PlayerStatsModel();

            OnInitialized.Invoke();
        }

        static event System.Action OnInitialized = delegate { };
    }
}
